#!/bin/bash
set -euo pipefail

# ─── intent-setup.sh ────────────────────────────────────────────────────────
# One-time setup for the intent computer on exe.dev.
# Run this after creating a VM with: ssh exe.dev new --name=<name>
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/<org>/intent-computer/main/deploy/exe-dev/intent-setup.sh | bash
#   OR
#   git clone ... && cd intent-computer && bash deploy/exe-dev/intent-setup.sh
# ─────────────────────────────────────────────────────────────────────────────

VAULT_DIR="${HOME}/Mind"
REPO_DIR="${HOME}/intent-computer"
REPO_URL="https://github.com/<org>/intent-computer.git"
NODE_MAJOR=20
DEPLOY_DIR="${REPO_DIR}/deploy/exe-dev"

echo "═══════════════════════════════════════════════════"
echo "  intent-computer setup for exe.dev"
echo "═══════════════════════════════════════════════════"
echo ""

# ─── 1. Install Node.js 20 via NodeSource ────────────────────────────────────
# Using NodeSource instead of nvm for systemd compatibility.
# nvm requires shell sourcing that doesn't work well with systemd ExecStart.

if ! command -v node &>/dev/null || [[ "$(node --version)" != v20.* ]]; then
    echo "[1/7] Installing Node.js ${NODE_MAJOR}..."
    curl -fsSL https://deb.nodesource.com/setup_${NODE_MAJOR}.x | sudo -E bash -
    sudo apt-get install -y nodejs
else
    echo "[1/7] Node.js $(node --version) already installed, skipping."
fi

# Verify node is in a systemd-friendly path
NODE_BIN="$(which node)"
echo "  node binary: ${NODE_BIN}"

# ─── 2. Install pnpm ────────────────────────────────────────────────────────

if ! command -v pnpm &>/dev/null; then
    echo "[2/7] Installing pnpm..."
    sudo npm install -g pnpm
else
    echo "[2/7] pnpm $(pnpm --version) already installed, skipping."
fi

# ─── 3. Clone and build intent-computer ─────────────────────────────────────

if [[ -d "${REPO_DIR}" ]]; then
    echo "[3/7] Updating existing intent-computer..."
    cd "${REPO_DIR}"
    git pull --ff-only
else
    echo "[3/7] Cloning intent-computer..."
    git clone "${REPO_URL}" "${REPO_DIR}"
    cd "${REPO_DIR}"
fi

echo "  Installing dependencies..."
pnpm install --frozen-lockfile

echo "  Building..."
pnpm build

# ─── 4. Initialize vault ────────────────────────────────────────────────────

if [[ ! -d "${VAULT_DIR}" ]]; then
    echo "[4/7] Initializing vault at ${VAULT_DIR}..."
    mkdir -p "${VAULT_DIR}"/{thoughts,inbox,ops/sessions,ops/observations,ops/tensions,ops/capsules,ops/methodology,self,templates}

    # Copy default templates
    cp "${REPO_DIR}/packages/plugin/src/templates/"*.md "${VAULT_DIR}/templates/" 2>/dev/null || true

    # Create minimal self files
    cat > "${VAULT_DIR}/self/identity.md" << 'IDENTITY'
---
description: "Agent identity — who I am and how I work"
---

# Identity

I am a cognitive companion running on the intent computer.
This vault is my memory. Wiki links are my connections.
I tend this garden between sessions via the heartbeat.
IDENTITY

    cat > "${VAULT_DIR}/self/goals.md" << 'GOALS'
---
description: "Current goals and active threads"
---

# Goals

## Active

- Get oriented — this is a fresh vault

## Next Session

- Run /arscontexta:setup to personalize the vault
GOALS

    cat > "${VAULT_DIR}/self/working-memory.md" << 'WM'
---
description: "Working memory — recent context carried between sessions"
---

# Working Memory

*Fresh vault. No working memory yet.*
WM

    cat > "${VAULT_DIR}/ops/morning-brief.md" << 'BRIEF'
---
description: "Morning brief — generated by the heartbeat"
---

# Morning Brief

*Awaiting first heartbeat run.*
BRIEF

    cat > "${VAULT_DIR}/ops/config.yaml" << 'CONFIG'
# Intent computer configuration
processing_depth: standard
pipeline_chaining: suggested

maintenance:
  orphan_threshold: 5
  inbox_threshold: 3
  stale_days: 30
  observation_threshold: 10
  tension_threshold: 5
  unprocessed_sessions: 5
CONFIG

    # Initialize git repo for vault
    cd "${VAULT_DIR}"
    git init
    git add -A
    git commit -m "initial vault"
    cd "${REPO_DIR}"
    echo "  Vault initialized at ${VAULT_DIR}"
else
    echo "[4/7] Vault already exists at ${VAULT_DIR}, skipping initialization."
fi

# ─── 5. Configure Claude CLI MCP server ─────────────────────────────────────

echo "[5/7] Configuring Claude CLI MCP server..."

CLAUDE_CONFIG_DIR="${HOME}/.claude"
mkdir -p "${CLAUDE_CONFIG_DIR}"

# Write MCP server configuration for Claude CLI
# Claude Code reads mcpServers from ~/.claude.json
CLAUDE_JSON="${HOME}/.claude.json"

NODE_PATH="$(which node)"
MCP_SERVER_PATH="${REPO_DIR}/packages/mcp-server/dist/index.js"

# Create or merge .claude.json with MCP server config
if [[ -f "${CLAUDE_JSON}" ]]; then
    # Merge into existing config using jq
    jq --arg node "${NODE_PATH}" --arg mcp "${MCP_SERVER_PATH}" --arg vault "${VAULT_DIR}" \
        '.mcpServers["intent-computer"] = {
            "command": $node,
            "args": [$mcp, "--vault", $vault]
        }' "${CLAUDE_JSON}" > "${CLAUDE_JSON}.tmp" && mv "${CLAUDE_JSON}.tmp" "${CLAUDE_JSON}"
else
    cat > "${CLAUDE_JSON}" << CLAUDEJSON
{
    "mcpServers": {
        "intent-computer": {
            "command": "${NODE_PATH}",
            "args": ["${MCP_SERVER_PATH}", "--vault", "${VAULT_DIR}"]
        }
    }
}
CLAUDEJSON
fi

echo "  Claude CLI configured to use intent-computer MCP server"

# ─── 6. Install systemd services ────────────────────────────────────────────

echo "[6/7] Installing systemd services..."

# Generate unit files with correct paths baked in
NODE_PATH="$(which node)"

# intent-heartbeat.service
sudo tee /etc/systemd/system/intent-heartbeat.service > /dev/null << HEARTBEAT_SVC
[Unit]
Description=Intent Computer Heartbeat
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=exedev
WorkingDirectory=/home/exedev/intent-computer
ExecStart=${NODE_PATH} ${REPO_DIR}/packages/heartbeat/dist/index.js --vault ${VAULT_DIR} --slot auto --max-actions 3
Environment=HOME=/home/exedev
Environment=PATH=${NODE_PATH%/*}:/home/exedev/.local/bin:/usr/local/bin:/usr/bin:/bin
Environment=INTENT_CLAUDE_PATH=/home/exedev/.local/bin/claude
Environment=NODE_ENV=production
# 30-minute timeout — heartbeat can run LLM calls via Claude CLI
TimeoutStartSec=1800
# Don't restart oneshot on failure — timer will fire again in 15 min
StandardOutput=journal
StandardError=journal
SyslogIdentifier=intent-heartbeat
HEARTBEAT_SVC

# intent-heartbeat.timer
sudo tee /etc/systemd/system/intent-heartbeat.timer > /dev/null << 'HEARTBEAT_TMR'
[Unit]
Description=Intent Computer Heartbeat Timer (every 15 minutes)

[Timer]
OnBootSec=2min
OnUnitActiveSec=15min
Persistent=true
RandomizedDelaySec=60

[Install]
WantedBy=timers.target
HEARTBEAT_TMR

# vault-web.service
sudo tee /etc/systemd/system/vault-web.service > /dev/null << VAULTWEB_SVC
[Unit]
Description=Intent Computer Vault Web UI
After=network-online.target
Wants=network-online.target

[Service]
Type=exec
User=exedev
WorkingDirectory=/home/exedev/intent-computer
ExecStart=${NODE_PATH} ${REPO_DIR}/packages/vault-web/dist/index.js --vault ${VAULT_DIR} --port 8080
Restart=on-failure
RestartSec=5
Environment=HOME=/home/exedev
Environment=PATH=${NODE_PATH%/*}:/usr/local/bin:/usr/bin:/bin
Environment=NODE_ENV=production
StandardOutput=journal
StandardError=journal
SyslogIdentifier=vault-web

[Install]
WantedBy=multi-user.target
VAULTWEB_SVC

# Reload and enable
sudo systemctl daemon-reload
sudo systemctl enable --now intent-heartbeat.timer
sudo systemctl enable --now vault-web.service

echo "  intent-heartbeat.timer: enabled (fires every 15 min)"
echo "  vault-web.service: enabled (port 8080)"

# ─── 7. Configure backup cron ───────────────────────────────────────────────

echo "[7/7] Configuring backup cron..."

# Add git auto-push every 6 hours (only if a remote is configured)
CRON_LINE="0 */6 * * * cd ${VAULT_DIR} && git add -A && git diff --cached --quiet || git commit -m 'auto-backup \$(date -u +\%Y-\%m-\%dT\%H:\%MZ)' && git push origin main 2>/dev/null || true"

# Idempotent cron installation
(crontab -l 2>/dev/null | grep -v 'intent.*auto-backup' || true; echo "${CRON_LINE}") | crontab -

echo "  Backup cron installed (every 6 hours, requires git remote)"
echo ""

# ─── Done ────────────────────────────────────────────────────────────────────

VM_NAME=$(hostname)
echo "═══════════════════════════════════════════════════"
echo "  Setup complete!"
echo ""
echo "  Vault:     ${VAULT_DIR}"
echo "  Web UI:    https://${VM_NAME}.exe.xyz/"
echo "  Heartbeat: systemctl status intent-heartbeat.timer"
echo "  Logs:      journalctl -u intent-heartbeat -f"
echo "  Web logs:  journalctl -u vault-web -f"
echo ""
echo "  Next steps:"
echo "    1. Add a git remote for backup:"
echo "       cd ~/Mind && git remote add origin <your-repo-url>"
echo "    2. SSH in and use Claude CLI interactively:"
echo "       ssh ${VM_NAME}.exe.dev"
echo "       claude"
echo "    3. Visit https://${VM_NAME}.exe.xyz/ to browse your vault"
echo "═══════════════════════════════════════════════════"
